training:
  num_workers: 10
  batch_size: 1024
  exp_name: ''
  epochs: 24
  lr: 0.1
  weight_decay: 0.0005 # 0.01 for training from scratch best result
  momentum: 0.9
  lr_scheduler: cyclic
  step_size: 10
  lr_milestones: ""
  lr_peak_epoch: 5
  gamma: 0.1
  label_smoothing: 0.0
  disable_logging: False
  supercloud: True #False
  decoder_train: center_crop_224_256
  decoder_val: center_crop_224_256
  granularity: per_class
  data_root: /mnt/cfs/datasets/transfer_datasets
logging:
  do_if_complete: False
  mmap_logdir: ""
model:
  arch: resnet18
  pretrained: False
  checkpoint: "" # override in command
  transfer: FIXED # Or NONE | FIXED | FULL
resolution:
  prog_resizing: False
  val_res: 224
data:
  dataset: AIRCRAFT
  train_path: aircraft/aircraft_train.beton
  val_path: aircraft/aircraft_test.beton
spurious:
  spurious_perc: 0 # do not embed spurious
  spurious_type: gaussian # gaussian or square
  spurious_file: meta_data/aircraft_uniform.npy
  gaussian_pattern_path: meta_data/gaussian_pattern.npy
  gaussian_scale: 0.01

